 [INFO   ] (2019-04-02 14:47:39) py-initexit             : -v flag specified on command line: extra verbose output
 [DEBUG  ] (2019-04-02 14:47:39) py-rc                   : reading rcfile 51_9reg.rc ...
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : DA Cycle rc-file (51_9reg.rc) loaded successfully
 [DEBUG  ] (2019-04-02 14:47:39) py-initexit             : DA Cycle settings have been validated succesfully
 [DEBUG  ] (2019-04-02 14:47:39) py-rc                   : reading rcfile da/rc/carbontracker_cosmo.rc ...
 [DEBUG  ] (2019-04-02 14:47:39) py-rc                   : Added rootdir to requested include: da/rc/NamingScheme.wp_Mar2011.rc
 [DEBUG  ] (2019-04-02 14:47:39) py-dasystem             : DA System Info rc-file (da/rc/carbontracker_cosmo.rc) loaded successfully
 [DEBUG  ] (2019-04-02 14:47:39) py-dasystem             : Data Assimilation System initialized: CarbonTracker CO2
 [INFO   ] (2019-04-02 14:47:39) py-observationoperator  : Observation Operator object initialized: ObservationOperator
 [INFO   ] (2019-04-02 14:47:39) py-obs                  : Observations object initialized: Observations baseclass
 [INFO   ] (2019-04-02 14:47:39) py-statevector          : Statevector object initialized: Baseclass Statevector 
 [INFO   ] (2019-04-02 14:47:39) py-base_optimizer       : Optimizer object initialized: Optimizer baseclass
 [INFO   ] (2019-04-02 14:47:39) py-template             : 

    ***************************************   Entering Pipeline     *************************************** 
  
 [INFO   ] (2019-04-02 14:47:39) py-pipeline             : 

    ***************************************   Initializing current cycle    *************************************** 
  
 [DEBUG  ] (2019-04-02 14:47:39) py-dasystem             : DA System Info settings have been validated succesfully
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : First time step in filter sequence
 [INFO   ] (2019-04-02 14:47:39) py-general              : Creating new directory /scratch/snx3000/parsenov/51_9reg
 [INFO   ] (2019-04-02 14:47:39) py-general              : Creating new directory /scratch/snx3000/parsenov/51_9reg/exec
 [INFO   ] (2019-04-02 14:47:39) py-general              : Creating new directory /scratch/snx3000/parsenov/51_9reg/input
 [INFO   ] (2019-04-02 14:47:39) py-general              : Creating new directory /scratch/snx3000/parsenov/51_9reg/output/20130401
 [INFO   ] (2019-04-02 14:47:39) py-general              : Creating new directory /scratch/snx3000/parsenov/51_9reg/analysis
 [INFO   ] (2019-04-02 14:47:39) py-general              : Creating new directory /scratch/snx3000/parsenov/51_9reg/jobs
 [INFO   ] (2019-04-02 14:47:39) py-general              : Creating new directory /scratch/snx3000/parsenov/51_9reg/restart
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : Succesfully created the file structure for the assimilation job
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : Copied regions file to the analysis directory: /store/empa/em05/parsenov/CTDAS/ctdas-cosmo/da/analysis/cosmo_9_reg_mittel_4.nc
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : Copied extended regions file to the analysis directory: /store/empa/em05/parsenov/CTDAS/ctdas-cosmo/da/analysis/cosmo_9_reg_mittel_4.nc
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : ===============================================================
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : DA Cycle start date is 2013-04-01 00:00
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : DA Cycle end date is 2013-04-07 23:00
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : DA Cycle final date is 2013-04-07 23:00
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : DA Cycle cycle length is 7
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : DA Cycle restart is False
 [INFO   ] (2019-04-02 14:47:39) py-initexit             : ===============================================================
 [DEBUG  ] (2019-04-02 14:47:39) py-statevector          : A TransCom  map on 1x1 degree was read from file /store/empa/em05/parsenov/CTDAS/ctdas-cosmo/da/analysis/cosmo_9_reg_mittel_4.nc
 [DEBUG  ] (2019-04-02 14:47:39) py-statevector          : A parameter map on 1x1 degree was read from file /store/empa/em05/parsenov/CTDAS/ctdas-cosmo/da/analysis/cosmo_9_reg_mittel_4.nc
 [DEBUG  ] (2019-04-02 14:47:39) py-statevector          : A dictionary to map grids to states and vice versa was created
 [DEBUG  ] (2019-04-02 14:47:39) py-statevector          : A matrix to map states to TransCom regions and vice versa was created
 [DEBUG  ] (2019-04-02 14:47:39) py-statevector          : A species mask was created, only the following species are recognized in this system:
 [DEBUG  ] (2019-04-02 14:47:39) py-statevector          :    ->    co2
 [INFO   ] (2019-04-02 14:47:39) py-pipeline             : 

    ***************************************   starting prepare_state    *************************************** 
  
 [DEBUG  ] (2019-04-02 14:47:40) py-statevector          : Cholesky decomposition has succeeded 
 [INFO   ] (2019-04-02 14:47:40) py-statevector          : Appr. degrees of freedom in covariance matrix is 16
 [DEBUG  ] (2019-04-02 14:47:40) py-statevector          : 51 new ensemble members were added to the state vector # 1
 [DEBUG  ] (2019-04-02 14:47:40) py-statevector          : Cholesky decomposition has succeeded 
 [INFO   ] (2019-04-02 14:47:40) py-statevector          : Appr. degrees of freedom in covariance matrix is 16
 [DEBUG  ] (2019-04-02 14:47:40) py-statevector          : 51 new ensemble members were added to the state vector # 2
 [DEBUG  ] (2019-04-02 14:47:40) py-statevector          : Creating new StateVector output file (/scratch/snx3000/parsenov/51_9reg/restart/savestate_20130401.nc)
 [INFO   ] (2019-04-02 14:47:40) py-statevector          : Successfully wrote the State Vector to file (/scratch/snx3000/parsenov/51_9reg/restart/savestate_20130401.nc) 
 [INFO   ] (2019-04-02 14:47:40) py-pipeline             : 

    ***************************************   starting sample_state    *************************************** 
  
 [INFO   ] (2019-04-02 14:47:40) py-pipeline             : Sampling model will be run over 2 cycles
 [INFO   ] (2019-04-02 14:47:40) py-pipeline             : 

    ***************************************   .....Ensemble Kalman Filter at lag 1
 [INFO   ] (2019-04-02 14:47:40) py-pipeline             : New simulation interval set : 
 [INFO   ] (2019-04-02 14:47:40) py-pipeline             :                   start date : 2013-04-01 00:00 
 [INFO   ] (2019-04-02 14:47:40) py-pipeline             :                   end   date : 2013-04-07 23:00 
 [INFO   ] (2019-04-02 14:47:40) py-pipeline             :                   file  stamp: 2013040100_2013040723 
 [DEBUG  ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : ObsPack dataset info read, proceeding with 4 netcdf files
 [DEBUG  ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Added 168 observations from file (brm_gpp1.2resp0.8br1.01) to the Data list
 [DEBUG  ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Added 168 observations from file (jfj_gpp1.2resp0.8br1.01) to the Data list
 [DEBUG  ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Added 168 observations from file (lhw_gpp1.2resp0.8br1.01) to the Data list
 [DEBUG  ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Added 168 observations from file (ssl_gpp1.2resp0.8br1.01) to the Data list
 [INFO   ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Observations list now holds 672 values
 [DEBUG  ] (2019-04-02 14:47:45) py-rc                   : reading rcfile /store/empa/em05/parsenov/obs/sites_weights_ctdas.rc ...
 [DEBUG  ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Model-data mismatch rejection threshold: 3 
 [WARNING] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Model-data mismatch scaling factor     : 1.000000 
 [DEBUG  ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Model-data mismatch site categories    : 8 
 [DEBUG  ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Added Model Data Mismatch to all samples 
 [DEBUG  ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Creating new observations file for ObservationOperator (/scratch/snx3000/parsenov/51_9reg/input/sample_coordinates_2013040100_2013040723.nc)
 [DEBUG  ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Successfully wrote data to obs file
 [INFO   ] (2019-04-02 14:47:45) py-obspack_globalviewplus2 : Sample input file for obs operator now in place [/scratch/snx3000/parsenov/51_9reg/input/sample_coordinates_2013040100_2013040723.nc]
 [DEBUG  ] (2019-04-02 14:47:45) py-observationoperator  : Creating new simulated observation file in ObservationOperator (/scratch/snx3000/parsenov/51_9reg/output/20130401/samples_simulated.2013040100_2013040723.nc)
 [INFO   ] (2019-04-02 14:47:45) py-observationoperator  : Multiplying emissions with parameters for lag 0
51_9reg
2013-04-01 00:00:00
Process "meteo" for chain "2013040100_0_168"
Process "icbc" for chain "2013040100_0_168"
Process "emissions" for chain "2013040100_0_168"
Process "biofluxes" for chain "2013040100_0_168"
Process "int2lm" for chain "2013040100_0_168"
Submitted batch job 12731757
sbatch: error: Currently unable to load job state information, retrying: Socket timed out on send/recv operation
Process "post_int2lm" for chain "2013040100_0_168"
Process "cosmo" for chain "2013040100_0_168"
sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)
>>> finished chain for good or bad! <<<
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : COSMO done!
IO Class CT_HDF not compiled, no HDF support!!!
IO Class CT_HDF not compiled, no HDF support!!!
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 001, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 002, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 003, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 004, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 005, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 006, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 007, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 008, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 009, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 010, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 011, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 013, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 012, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 014, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 015, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 022, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 019, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 016, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 025, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 029, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 027, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 018, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 024, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 026, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 030, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 021, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 031, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 023, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 033, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 034, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 035, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 028, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 032, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 020, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 017, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 036, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 041, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 042, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 043, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 040, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 039, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 037, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 038, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 044, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 045, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 047, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 048, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 049, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 046, time 2013040100
 [INFO   ] (2019-04-02 19:51:48) py-observationoperator  : Extracting output for ens 050, time 2013040100
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 3 required positional arguments: 'stdout', 'stderr', and 'returncode'

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_043-GPP_043+RESP_043+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_043,GPP_043,RESP_043,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_043_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_033-GPP_033+RESP_033+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_033,GPP_033,RESP_033,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_033_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_003-GPP_003+RESP_003+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_003,GPP_003,RESP_003,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_003_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_031-GPP_031+RESP_031+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_031,GPP_031,RESP_031,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_031_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_030-GPP_030+RESP_030+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_030,GPP_030,RESP_030,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_030_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_009-GPP_009+RESP_009+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_009,GPP_009,RESP_009,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_009_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_050-GPP_050+RESP_050+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_050,GPP_050,RESP_050,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_050_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_040-GPP_040+RESP_040+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_040,GPP_040,RESP_040,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_040_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_022-GPP_022+RESP_022+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_022,GPP_022,RESP_022,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_022_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_047-GPP_047+RESP_047+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_047,GPP_047,RESP_047,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_047_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_013-GPP_013+RESP_013+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_013,GPP_013,RESP_013,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_013_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_038-GPP_038+RESP_038+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_038,GPP_038,RESP_038,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_038_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_007-GPP_007+RESP_007+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_007,GPP_007,RESP_007,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_007_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_023-GPP_023+RESP_023+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_023,GPP_023,RESP_023,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_023_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_041-GPP_041+RESP_041+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_041,GPP_041,RESP_041,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_041_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_016-GPP_016+RESP_016+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_016,GPP_016,RESP_016,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_016_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_034-GPP_034+RESP_034+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_034,GPP_034,RESP_034,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_034_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_002-GPP_002+RESP_002+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_002,GPP_002,RESP_002,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_002_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-3:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_032-GPP_032+RESP_032+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_032,GPP_032,RESP_032,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_032_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_008-GPP_008+RESP_008+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_008,GPP_008,RESP_008,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_008_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_018-GPP_018+RESP_018+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_018,GPP_018,RESP_018,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_018_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_027-GPP_027+RESP_027+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_027,GPP_027,RESP_027,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_027_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_029-GPP_029+RESP_029+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_029,GPP_029,RESP_029,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_029_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_020-GPP_020+RESP_020+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_020,GPP_020,RESP_020,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_020_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_017-GPP_017+RESP_017+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_017,GPP_017,RESP_017,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_017_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_049-GPP_049+RESP_049+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_049,GPP_049,RESP_049,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_049_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_035-GPP_035+RESP_035+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_035,GPP_035,RESP_035,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_035_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_004-GPP_004+RESP_004+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_004,GPP_004,RESP_004,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_004_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_024-GPP_024+RESP_024+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_024,GPP_024,RESP_024,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_024_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_039-GPP_039+RESP_039+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_039,GPP_039,RESP_039,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_039_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_025-GPP_025+RESP_025+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_025,GPP_025,RESP_025,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_025_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_044-GPP_044+RESP_044+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_044,GPP_044,RESP_044,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_044_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_010-GPP_010+RESP_010+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_010,GPP_010,RESP_010,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_010_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_014-GPP_014+RESP_014+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_014,GPP_014,RESP_014,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_014_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_028-GPP_028+RESP_028+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_028,GPP_028,RESP_028,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_028_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-15:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_015-GPP_015+RESP_015+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_015,GPP_015,RESP_015,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_015_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-16:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_042-GPP_042+RESP_042+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_042,GPP_042,RESP_042,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_042_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-44:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_026-GPP_026+RESP_026+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_026,GPP_026,RESP_026,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_026_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-27:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_036-GPP_036+RESP_036+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_036,GPP_036,RESP_036,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_036_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_006-GPP_006+RESP_006+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_006,GPP_006,RESP_006,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_006_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_011-GPP_011+RESP_011+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_011,GPP_011,RESP_011,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_011_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-7:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_019-GPP_019+RESP_019+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_019,GPP_019,RESP_019,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_019_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-20:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_045-GPP_045+RESP_045+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_045,GPP_045,RESP_045,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_045_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-46:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_037-GPP_037+RESP_037+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_037,GPP_037,RESP_037,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_037_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-37:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_048-GPP_048+RESP_048+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_048,GPP_048,RESP_048,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_048_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-51:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_046-GPP_046+RESP_046+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_046,GPP_046,RESP_046,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_046_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-49:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_021-GPP_021+RESP_021+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_021,GPP_021,RESP_021,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_021_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-22:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_012-GPP_012+RESP_012+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_012,GPP_012,RESP_012,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_012_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-13:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Error in calling operator expr with:
>>> cdo -O expr,'CO2=(BG_005-GPP_005+RESP_005+CO2_A_CH+CO2_A)/(1.-QV)' -remapnn,lon=7.99_lat=46.54 -selname,QV,BG_005,GPP_005,RESP_005,CO2_A_CH,CO2_A /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/CO2_jfj_005_2013040100.nc<<<
STDOUT:
STDERR:cdo: /store/empa/em05/parsenov/python-env/bin/../lib/libuuid.so.1: no version information available (required by cdo)

cdo (Abort): Input file /scratch/snx3000/parsenov/51_9reg/2013040100_0_168/cosmo/output/lffd2013040100.nc of process selname does not exists

Process ForkPoolWorker-6:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-29:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-38:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-12:
Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/store/empa/em05/parsenov/python-env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
